### ISSUE TITLE
deploy-api-version-1

### ISSUE THREAD

**Issue by Ayco23** [mendix/docs#7129] opened 2024-01-18 12:13 UTC
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deploy-api-version-1](https://docs.mendix.com/apidocs-mxsdk/apidocs/deploy-api/)

Document link: [deploy-api-1.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/deploy-api-1.md)

## My Issue/Suggestion
Something in the documentation is wrong. The possible Environment status 'notdeployed' is not documented and should be added.

In more detail:
According to the [documentation to get Environment info](https://docs.mendix.com/apidocs-mxsdk/apidocs/deploy-api/#343-output), 

The docs state that the status is one of the following:
Status (String): Status of the environment. Possible values: Empty, Stopped, Running.

However, an environment which isn't deployed yet, returns the state 'notdeployed', see:
```
{
    "id": "33a2bf7b-29b5-4405-a0de-7b867c5bd6b0",
    "appId": "908c7dc7-173b-4f35-a173-168ecce61598",
    "name": "Production",
    "state": "notdeployed",
    "isProduction": true,
    "url": "https://myfleetsupport100.apps.eu-1c.mendixcloud.com",
    "planName": "M21-STANDARD"
}
```

**Comment by dbreseman** [comment] 2024-01-23 12:52
Hi @Ayco23, thanks for your feedback. Could you please confirm if you're using the Deploy API v1? From the output you've provided, it looks like you might be using v4. You can see the relevant documentation for v4 here: https://docs.mendix.com/apidocs-mxsdk/apidocs/deploy-api-4/#4-api-reference.

**Comment by dbreseman** [comment] 2024-02-02 15:13
Hi @Ayco23, please let me know if this helped clarify things or if I can provide any other information. I will keep this issue open for another week. If I haven't received a reply by then, I will go ahead and close this issue. Thanks in advance!

**Comment by Ayco23** [comment] 2024-02-02 15:22
Hi, sorry for my late response. 
I was indeed using the v4, my bad :<

**Comment by dbreseman** [comment] 2024-02-02 15:24
No worries! Thanks for reaching out, and glad to hear the issue is resolved!

**Closed as completed by dbreseman** 2024-02-02 15:24 UTC
