### ISSUE TITLE
Broken images in page document templates

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/docs#8779] opened 2024-12-10 14:14 UTC
https://docs.mendix.com/refguide/document-templates/

![image](https://github.com/user-attachments/assets/15d2278a-9dac-4fc9-a35f-394338a0a9e7)

**Comment by Yiyun333** [comment] 2024-12-13 13:40
Hi @Andries-Smit,

Thanks a lot for reporting this! The issue is fixed in this PR: https://github.com/mendix/docs/pull/8782. You will be able to see the fixed images online by the end of the today.

Best,
Yiyun

**Closed as completed by Yiyun333** 2024-12-13 13:40 UTC
