### ISSUE TITLE
offline-synchronization

### ISSUE THREAD

**Issue by oriana-nerberka** [mendix/docs#5335] opened 2022-11-22 13:28 UTC
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [offline-synchronization](https://docs.mendix.com/refguide/mobile/using-mobile-capabilities/offlinefirst-data/synchronization/)

Document link: [synchronization.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/synchronization.md)

## My Issue/Suggestion

```
2.1.3 Selective Synchronization
Selective synchronization can only be done through a Synchronize action inside a nanoflow. In this mode, a specific set of objects will be synchronized. These objects can be either all unsynchronized objects when the [synchronize unsynchronized objects](https://docs.mendix.com/refguide/synchronize/#unsynchronized-objects) mode is selected, or a manually selected set of objects when the [synchronize selected object(s)](https://docs.mendix.com/refguide/synchronize/#selected-objects) mode is selected.

Deleted objects cannot be synchronized using selective synchronization.
```

This paragraph implies that the 'synchronize unsynchronized objects' (SUO) sync works like a selective sync, or is indeed a version of selective sync. My understanding was that the SUO sync is more aligned with a full sync; all dirty, committed objects will be uploaded and then for those specific tables the synchronization configuration will be applied to the download phase. 

In a selective sync the synchronization configuration is ignored, and I think grouping the SUO under selective sync makes the difference between the modes more confusing for learners. 

Suggested change: Remove the reference to the SUO from selective sync, and keep any details about it in it's own section (which is 2.1.2).

**Comment by ekrem-aktas** [comment] 2022-11-30 09:57
Hi @oriana-nerberka 

The "Synchronize unsynchronized objects" mode is intended to work like selective sync, where it ignores the synchronization configuration. Do you have a specific case where you observe otherwise? Then it may be a bug to address

**Comment by oriana-nerberka** [comment] 2022-11-30 10:08
Hey @ekrem-aktas, no, I haven't run a test, that was always just my understanding. I must have heard it somehow and committed it to my own memory. Glad to be corrected - thanks!

**Comment by ekrem-aktas** [comment] 2022-11-30 10:50
Thank you @oriana-nerberka, Let us know if you encounter an unexpected behavior ;)

**Comment by ConnorLand** [comment] 2023-10-19 13:45
Closing this as we have not observed an unexpected behavior and could not duplicate it.

**Closed as completed by ConnorLand** 2023-10-19 13:45 UTC
